=== fastmcp-me/dotnet-test-assignment/WeatherMcpServer/Schemas/OpenWeather/geo-direct.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "https://api.openweathermap.org/geo/1.0/direct",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "name": {
        "type": "string"
      },
      "local_names": {
        "type": "object",
        "properties": {
          "ia": {
            "type": "string"
          },
          "av": {
            "type": "string"
          },
          "feature_name": {
            "type": "string"
          },
          "jv": {
            "type": "string"
          },
          "kg": {
            "type": "string"
          },
          "ab": {
            "type": "string"
          },
          "en": {
            "type": "string"
          },
          "os": {
            "type": "string"
          },
          "qu": {
            "type": "string"
          },
          "yi": {
            "type": "string"
          },
          "ak": {
            "type": "string"
          },
          "tg": {
            "type": "string"
          },
          "sw": {
            "type": "string"
          },
          "el": {
            "type": "string"
          },
          "ar": {
            "type": "string"
          },
          "su": {
            "type": "string"
          },
          "uz": {
            "type": "string"
          },
          "hu": {
            "type": "string"
          },
          "io": {
            "type": "string"
          },
          "nl": {
            "type": "string"
          },
          "an": {
            "type": "string"
          },
          "ml": {
            "type": "string"
          },
          "fy": {
            "type": "string"
          },
          "kn": {
            "type": "string"
          },
          "sl": {
            "type": "string"
          },
          "eu": {
            "type": "string"
          },
          "uk": {
            "type": "string"
          },
          "ce": {
            "type": "string"
          },
          "st": {
            "type": "string"
          },
          "id": {
            "type": "string"
          },
          "it": {
            "type": "string"
          },
          "ay": {
            "type": "string"
          },
          "ku": {
            "type": "string"
          },
          "fa": {
            "type": "string"
          },
          "bg": {
            "type": "string"
          },
          "zu": {
            "type": "string"
          },
          "pl": {
            "type": "string"
          },
          "br": {
            "type": "string"
          },
          "mn": {
            "type": "string"
          },
          "kl": {
            "type": "string"
          },
          "ga": {
            "type": "string"
          },
          "vi": {
            "type": "string"
          },
          "pt": {
            "type": "string"
          },
          "gl": {
            "type": "string"
          },
          "dz": {
            "type": "string"
          },
          "so": {
            "type": "string"
          },
          "lt": {
            "type": "string"
          },
          "co": {
            "type": "string"
          },
          "th": {
            "type": "string"
          },
          "am": {
            "type": "string"
          },
          "az": {
            "type": "string"
          },
          "yo": {
            "type": "string"
          },
          "fr": {
            "type": "string"
          },
          "te": {
            "type": "string"
          },
          "cs": {
            "type": "string"
          },
          "mg": {
            "type": "string"
          },
          "bo": {
            "type": "string"
          },
          "ta": {
            "type": "string"
          },
          "bs": {
            "type": "string"
          },
          "kw": {
            "type": "string"
          },
          "tl": {
            "type": "string"
          },
          "da": {
            "type": "string"
          },
          "iu": {
            "type": "string"
          },
          "sr": {
            "type": "string"
          },
          "es": {
            "type": "string"
          },
          "tr": {
            "type": "string"
          },
          "hy": {
            "type": "string"
          },
          "no": {
            "type": "string"
          },
          "fo": {
            "type": "string"
          },
          "sv": {
            "type": "string"
          },
          "sq": {
            "type": "string"
          },
          "se": {
            "type": "string"
          },
          "oc": {
            "type": "string"
          },
          "mt": {
            "type": "string"
          },
          "ln": {
            "type": "string"
          },
          "hi": {
            "type": "string"
          },
          "wa": {
            "type": "string"
          },
          "mk": {
            "type": "string"
          },
          "af": {
            "type": "string"
          },
          "ht": {
            "type": "string"
          },
          "ko": {
            "type": "string"
          },
          "lv": {
            "type": "string"
          },
          "ca": {
            "type": "string"
          },
          "eo": {
            "type": "string"
          },
          "nb": {
            "type": "string"
          },
          "la": {
            "type": "string"
          },
          "ka": {
            "type": "string"
          },
          "ps": {
            "type": "string"
          },
          "ur": {
            "type": "string"
          },
          "sc": {
            "type": "string"
          },
          "sh": {
            "type": "string"
          },
          "hr": {
            "type": "string"
          },
          "ro": {
            "type": "string"
          },
          "dv": {
            "type": "string"
          },
          "bi": {
            "type": "string"
          },
          "cv": {
            "type": "string"
          },
          "wo": {
            "type": "string"
          },
          "gn": {
            "type": "string"
          },
          "ky": {
            "type": "string"
          },
          "ja": {
            "type": "string"
          },
          "mi": {
            "type": "string"
          },
          "ms": {
            "type": "string"
          },
          "na": {
            "type": "string"
          },
          "lg": {
            "type": "string"
          },
          "kk": {
            "type": "string"
          },
          "is": {
            "type": "string"
          },
          "gv": {
            "type": "string"
          },
          "be": {
            "type": "string"
          },
          "fi": {
            "type": "string"
          },
          "bn": {
            "type": "string"
          },
          "ru": {
            "type": "string"
          },
          "zh": {
            "type": "string"
          },
          "sk": {
            "type": "string"
          },
          "vo": {
            "type": "string"
          },
          "mr": {
            "type": "string"
          },
          "ch": {
            "type": "string"
          },
          "li": {
            "type": "string"
          },
          "ba": {
            "type": "string"
          },
          "sm": {
            "type": "string"
          },
          "cu": {
            "type": "string"
          },
          "ty": {
            "type": "string"
          },
          "et": {
            "type": "string"
          },
          "sg": {
            "type": "string"
          },
          "tk": {
            "type": "string"
          },
          "nn": {
            "type": "string"
          },
          "ug": {
            "type": "string"
          },
          "za": {
            "type": "string"
          },
          "he": {
            "type": "string"
          },
          "gd": {
            "type": "string"
          },
          "kv": {
            "type": "string"
          },
          "ascii": {
            "type": "string"
          },
          "cy": {
            "type": "string"
          },
          "ss": {
            "type": "string"
          },
          "de": {
            "type": "string"
          },
          "ie": {
            "type": "string"
          },
          "my": {
            "type": "string"
          },
          "tt": {
            "type": "string"
          }
        },
        "required": [
          "en"
        ]
      },
      "lat": {
        "type": "number"
      },
      "lon": {
        "type": "number"
      },
      "country": {
        "type": "string"
      },
      "state": {
        "type": "string"
      }
    },
    "required": [
      "name",
      "local_names",
      "lat",
      "lon",
      "country",
      "state"
    ]
  }
}

=== fastmcp-me/dotnet-test-assignment/WeatherMcpServer.Tests/Responses/OpenWeather/geo-direct.json
[
  {
    "name": "Moscow",
    "local_names": {
      "is": "Moskva",
      "iu": "ᒨᔅᑯ",
      "ps": "مسکو",
      "br": "Moskov",
      "el": "Μόσχα",
      "la": "Moscua",
      "mg": "Moskva",
      "tt": "Мәскәү",
      "th": "มอสโก",
      "ca": "Moscou",
      "lt": "Maskva",
      "sk": "Moskva",
      "et": "Moskva",
      "ss": "Moscow",
      "de": "Moskau",
      "za": "Moscow",
      "ascii": "Moscow",
      "ka": "მოსკოვი",
      "io": "Moskva",
      "my": "မော်စကိုမြို့",
      "da": "Moskva",
      "se": "Moskva",
      "nb": "Moskva",
      "mk": "Москва",
      "dz": "མོསི་ཀོ",
      "zh": "莫斯科",
      "ur": "ماسکو",
      "sw": "Moscow",
      "ty": "Moscou",
      "vi": "Mát-xcơ-va",
      "es": "Moscú",
      "av": "Москва",
      "ar": "موسكو",
      "kk": "Мәскеу",
      "sv": "Moskva",
      "dv": "މޮސްކޯ",
      "feature_name": "Moscow",
      "st": "Moscow",
      "af": "Moskou",
      "he": "מוסקווה",
      "ia": "Moscova",
      "tr": "Moskova",
      "uk": "Москва",
      "li": "Moskou",
      "tk": "Moskwa",
      "yi": "מאסקווע",
      "ht": "Moskou",
      "bn": "মস্কো",
      "sg": "Moscow",
      "yo": "Mọsko",
      "so": "Moskow",
      "ml": "മോസ്കോ",
      "ak": "Moscow",
      "fi": "Moskova",
      "kw": "Moskva",
      "oc": "Moscòu",
      "gl": "Moscova - Москва",
      "lv": "Maskava",
      "ab": "Москва",
      "en": "Moscow",
      "na": "Moscow",
      "ky": "Москва",
      "ln": "Moskú",
      "ie": "Moskwa",
      "bg": "Москва",
      "co": "Moscù",
      "az": "Moskva",
      "sr": "Москва",
      "cy": "Moscfa",
      "hu": "Moszkva",
      "ch": "Moscow",
      "ms": "Moscow",
      "bi": "Moskow",
      "kn": "ಮಾಸ್ಕೋ",
      "gv": "Moscow",
      "ru": "Москва",
      "ja": "モスクワ",
      "fo": "Moskva",
      "mi": "Mohikau",
      "ko": "모스크바",
      "ku": "Moskow",
      "ug": "Moskwa",
      "wo": "Mosku",
      "pl": "Moskwa",
      "zu": "IMoskwa",
      "id": "Moskwa",
      "tg": "Маскав",
      "ta": "மாஸ்கோ",
      "eo": "Moskvo",
      "pt": "Moscou",
      "ce": "Москох",
      "sl": "Moskva",
      "sh": "Moskva",
      "fy": "Moskou",
      "am": "ሞስኮ",
      "te": "మాస్కో",
      "sm": "Moscow",
      "kv": "Мӧскуа",
      "no": "Moskva",
      "wa": "Moscou",
      "kl": "Moskva",
      "qu": "Moskwa",
      "gn": "Mosku",
      "bs": "Moskva",
      "it": "Mosca",
      "bo": "མོ་སི་ཁོ།",
      "nl": "Moskou",
      "lg": "Moosko",
      "mr": "मॉस्को",
      "jv": "Moskwa",
      "ba": "Мәскәү",
      "an": "Moscú",
      "uz": "Moskva",
      "fr": "Moscou",
      "sq": "Moska",
      "fa": "مسکو",
      "ay": "Mosku",
      "hi": "मास्को",
      "mn": "Москва",
      "hr": "Moskva",
      "eu": "Mosku",
      "nn": "Moskva",
      "ro": "Moscova",
      "ga": "Moscó",
      "cu": "Москъва",
      "cs": "Moskva",
      "os": "Мæскуы",
      "cv": "Мускав",
      "hy": "Մոսկվա",
      "be": "Масква",
      "su": "Moskwa",
      "mt": "Moska",
      "sc": "Mosca",
      "vo": "Moskva",
      "kg": "Moskva",
      "tl": "Moscow",
      "gd": "Moscobha"
    },
    "lat": 55.7504461,
    "lon": 37.6174943,
    "country": "RU",
    "state": "Moscow"
  }
]
